[project]
name = "orders"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "common",
    "tinkoff",
]

[tool.uv.sources]
common = { workspace = true }
tinkoff = { workspace = true }
