[project]
name = "tinkoff"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cachetools>=5.2.0,<6",
    "grpcio>=1.59.3,<2",
    "protobuf>=4.25.1,<5",
    "python-dateutil>=2.8.2,<3",
    "deprecation>=2.1.0,<3",
]
