# version: "3.9"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      KAFKA_OPTS: "-Dzookeeper.root.logger=WARN"
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    links:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOSTNAME: kafka
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
      KAFKA_LOG4J_LOGGERS: >-
        org.apache.zookeeper=WARN, kafka.controller=WARN, kafka.log.LogCleaner=WARN, state.change.logger=WARN, org.apache.kafka.server.log.internals.LogCleaner=WARN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock%
    healthcheck:
      test: [ "CMD", "bash", "-c", "echo > /dev/tcp/localhost/29092" ]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 30s

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - 8090:8080
      - 127.0.0.1:8080:8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    links:
      - kafka
      - zookeeper
    restart: unless-stopped

  # LOGGING

  loki:
    container_name: loki
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/config.yaml

  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    volumes:
      # !! Make sure this line is present and correct !!
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log:/var/log:ro
      - ./promtail-positions:/tmp/positions:rw
      - ./promtail-config.yaml:/etc/promtail/local-config.yaml
    command: -config.file=/etc/promtail/local-config.yaml

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/grafana-data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin

  # APP SERVICES

  ingest:
    build:
      context: .
      dockerfile: ingest/Dockerfile
    container_name: ingest
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
      KAFKA_TOPIC_RAW: market.raw
      TINKOFF_TOKEN: ${TINKOFF_TOKEN}
      DEMO: ${DEMO}
    volumes:
      - ./common:/app/common:ro
    restart: unless-stopped

  processing:
    build:
      context: .
      dockerfile: processing/Dockerfile
    container_name: processing
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
    restart: unless-stopped

  tick-storage:
    build:
      context: .
      dockerfile: tick-storage/Dockerfile
    container_name: tick-storage
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
    restart: unless-stopped
    volumes:
      - ./storage/ticks:/app/data

  strategies:
    build:
      context: .
      dockerfile: strategies/Dockerfile
    container_name: strategies
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
      TINKOFF_TOKEN: ${TINKOFF_TOKEN}
    restart: unless-stopped

  orders:
    build:
      context: .
      dockerfile: orders/Dockerfile
    container_name: orders
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
      TINKOFF_TOKEN: ${TINKOFF_TOKEN}
    restart: unless-stopped
