[project]
name = "common"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic-settings>=2.12.0",
    "structlog>=25.5.0",
    "aiokafka>=0.12.0",
    "dotenv>=0.9.9",
]
